<table class="row collapsed footer" style="border-spacing: 0; border-collapse: collapse; vertical-align: top; text-align: left; width: 100%; position: relative; display: table; padding: 0;"><tbody><tr style="vertical-align: top; text-align: left; padding: 0;" align="left"><th class="small-12 large-12 columns first last" style="width: 564px; color: #5F5F5F; font-family: Roboto, Helvetica, Arial, sans-serif; font-weight: 300; text-align: left; line-height: 1.3; font-size: 14px; margin: 0 auto; padding: 0 16px 16px;" align="left">
            <table style="border-spacing: 0; border-collapse: collapse; vertical-align: top; text-align: left; width: 100%; padding: 0;"><tr style="vertical-align: top; text-align: left; padding: 0;" align="left"><th style="color: #5F5F5F; font-family: Roboto, Helvetica, Arial, sans-serif; font-weight: 300; text-align: left; line-height: 1.3; font-size: 14px; margin: 0; padding: 0;" align="left">
                        <table class="spacer" style="border-spacing: 0; border-collapse: collapse; vertical-align: top; text-align: left; width: 100%; padding: 0;"><tbody><tr style="vertical-align: top; text-align: left; padding: 0;" align="left"><td height="16px" style="font-size: 16px; line-height: 16px; word-wrap: break-word; -webkit-hyphens: auto; -moz-hyphens: auto; hyphens: auto; border-collapse: collapse !important; vertical-align: top; text-align: left; mso-line-height-rule: exactly; color: #5F5F5F; font-family: Roboto, Helvetica, Arial, sans-serif; font-weight: 300; margin: 0; padding: 0;" align="left" valign="top"> </td>
                            </tr></tbody></table><table class="spacer" style="border-spacing: 0; border-collapse: collapse; vertical-align: top; text-align: left; width: 100%; padding: 0;"><tbody><tr style="vertical-align: top; text-align: left; padding: 0;" align="left"><td height="16px" style="font-size: 16px; line-height: 16px; word-wrap: break-word; -webkit-hyphens: auto; -moz-hyphens: auto; hyphens: auto; border-collapse: collapse !important; vertical-align: top; text-align: left; mso-line-height-rule: exactly; color: #5F5F5F; font-family: Roboto, Helvetica, Arial, sans-serif; font-weight: 300; margin: 0; padding: 0;" align="left" valign="top"> </td>
                            </tr></tbody></table><p class="text-center" style="font-weight: 400; text-align: center; color: #5F5F5F; font-family: Roboto, Helvetica, Arial, sans-serif; line-height: 1.3; font-size: 14px; margin: 0 0 10px; padding: 0;" align="center">Download Our <span style="color: red;">Apps</span><br /><a href="{{ config('misc.app.android-native.app_url') }}" style="color: #2199e8; font-family: Roboto, Helvetica, Arial, sans-serif; font-weight: normal; text-align: left; line-height: 1.3; text-decoration: none; margin: 0; padding: 0;"><img src="{!! asset('assets/img/email/android.png') !!}" alt="DaktarBhai - Google Play Store" style="display: inline-block; outline: none; text-decoration: none; -ms-interpolation-mode: bicubic; width: auto; max-width: 100%; clear: both; padding: 5px 0 10px; border: none;" /></a></p>
                        <center data-parsed="" style="width: 100%; min-width: 532px; background: #222222;">
                            <table align="center" class="menu float-center" style="border-spacing: 0; border-collapse: collapse; vertical-align: top; text-align: center; width: auto !important; float: none; margin: 0 auto; padding: 0;"><tr style="vertical-align: top; text-align: left; padding: 0;" align="left"><td style="word-wrap: break-word; -webkit-hyphens: auto; -moz-hyphens: auto; hyphens: auto; border-collapse: collapse !important; vertical-align: top; text-align: left; color: #5F5F5F; font-family: Roboto, Helvetica, Arial, sans-serif; font-weight: 300; line-height: 1.3; font-size: 14px; margin: 0; padding: 0;" align="left" valign="top">
                                        <table style="border-spacing: 0; border-collapse: collapse; vertical-align: top; text-align: left; width: 100%; padding: 0;"><tr style="vertical-align: top; text-align: left; padding: 0;" align="left"><th class="menu-item float-center" style="float: none; text-align: center; color: #5F5F5F; font-family: Roboto, Helvetica, Arial, sans-serif; font-weight: 300; line-height: 1.3; font-size: 14px; margin: 0 auto; padding: 10px;" align="center">
                                                    <a href="{{ config('misc.app.social.facebook') }}" style="color: #2199e8; font-family: Roboto, Helvetica, Arial, sans-serif; font-weight: normal; text-align: left; line-height: 1.3; text-decoration: none; margin: 0; padding: 0;"><img src="{!! asset('assets/img/email/facebook.png') !!}" alt="facebook" style="outline: none; text-decoration: none; -ms-interpolation-mode: bicubic; width: auto; max-width: 100%; clear: both; display: block; border: none;" /></a>
                                                </th>
                                                <th class="menu-item float-center" style="float: none; text-align: center; color: #5F5F5F; font-family: Roboto, Helvetica, Arial, sans-serif; font-weight: 300; line-height: 1.3; font-size: 14px; margin: 0 auto; padding: 10px;" align="center">
                                                    <a href="{{ config('misc.app.social.twitter') }}" style="color: #2199e8; font-family: Roboto, Helvetica, Arial, sans-serif; font-weight: normal; text-align: left; line-height: 1.3; text-decoration: none; margin: 0; padding: 0;"><img src="{!! asset('assets/img/email/twitter.png') !!}" alt="twitter" style="outline: none; text-decoration: none; -ms-interpolation-mode: bicubic; width: auto; max-width: 100%; clear: both; display: block; border: none;" /></a>
                                                </th>
                                                {{--<th class="menu-item float-center" style="float: none; text-align: center; color: #5F5F5F; font-family: Roboto, Helvetica, Arial, sans-serif; font-weight: 300; line-height: 1.3; font-size: 14px; margin: 0 auto; padding: 10px;" align="center">--}}
                                                    {{--<a href="undefined" style="color: #2199e8; font-family: Roboto, Helvetica, Arial, sans-serif; font-weight: normal; text-align: left; line-height: 1.3; text-decoration: none; margin: 0; padding: 0;"><img src="{!! asset('assets/img/email/google.png') !!}" alt="google+" style="outline: none; text-decoration: none; -ms-interpolation-mode: bicubic; width: auto; max-width: 100%; clear: both; display: block; border: none;" /></a>--}}
                                                {{--</th>--}}
                                                <th class="menu-item float-center" style="float: none; text-align: center; color: #5F5F5F; font-family: Roboto, Helvetica, Arial, sans-serif; font-weight: 300; line-height: 1.3; font-size: 14px; margin: 0 auto; padding: 10px;" align="center">
                                                    <a href="{{ config('misc.app.social.youtube') }}" style="color: #2199e8; font-family: Roboto, Helvetica, Arial, sans-serif; font-weight: normal; text-align: left; line-height: 1.3; text-decoration: none; margin: 0; padding: 0;"><img src="{!! asset('assets/img/email/youtube.png') !!}" alt="youtube" style="outline: none; text-decoration: none; -ms-interpolation-mode: bicubic; width: auto; max-width: 100%; clear: both; display: block; border: none;" /></a>
                                                </th>
                                            </tr></table></td>
                                </tr></table></center>
                    </th>
                    <th class="expander" style="visibility: hidden; width: 0; color: #5F5F5F; font-family: Roboto, Helvetica, Arial, sans-serif; font-weight: 300; text-align: left; line-height: 1.3; font-size: 14px; margin: 0; padding: 0;" align="left"></th>
                </tr></table></th>
    </tr></tbody></table></td>
</tr></tbody></table></center>
</td>
</tr></table></body>
</html>
