@extends('frontend.layouts.emails.master')

@section('title', 'Daktarbhai - Get Panel Hospital discount')
@section('content')
    <table class="spacer" style="border-spacing: 0; border-collapse: collapse; vertical-align: top; text-align: left; width: 100%; padding: 0;"><tbody><tr style="vertical-align: top; text-align: left; padding: 0;" align="left"><td height="16px" style="font-size: 16px; line-height: 16px; word-wrap: break-word; -webkit-hyphens: auto; -moz-hyphens: auto; hyphens: auto; border-collapse: collapse !important; vertical-align: top; text-align: left; mso-line-height-rule: exactly; color: #5F5F5F; font-family: Roboto, Helvetica, Arial, sans-serif; font-weight: 300; margin: 0; padding: 0;" align="left" valign="top"> </td>
        </tr></tbody></table><table class="row" style="border-spacing: 0; border-collapse: collapse; vertical-align: top; text-align: left; width: 100%; position: relative; display: table; padding: 0;"><tbody><tr style="vertical-align: top; text-align: left; padding: 0;" align="left"><th class="small-12 large-12 columns first last" style="width: 564px; color: #5F5F5F; font-family: Roboto, Helvetica, Arial, sans-serif; font-weight: 300; text-align: left; line-height: 1.3; font-size: 14px; margin: 0 auto; padding: 0 16px 16px;" align="left">
                <table style="border-spacing: 0; border-collapse: collapse; vertical-align: top; text-align: left; width: 100%; padding: 0;"><tr style="vertical-align: top; text-align: left; padding: 0;" align="left"><th style="color: #5F5F5F; font-family: Roboto, Helvetica, Arial, sans-serif; font-weight: 300; text-align: left; line-height: 1.3; font-size: 14px; margin: 0; padding: 0;" align="left">
                            <h6 style="color: #666666; font-family: Roboto, Helvetica, Arial, sans-serif; font-weight: 500; text-align: left; line-height: 1.3; word-wrap: normal; font-size: 14px; margin: 0 0 0 20px; padding: 5px 10px 5px 0;" align="left">
                                You have successfully <span style="color: #ed1c24;">availed Discount</span> from the following hospital/ diagnostic center..
                            </h6>
                        </th>
                        <th class="expander" style="visibility: hidden; width: 0; color: #5F5F5F; font-family: Roboto, Helvetica, Arial, sans-serif; font-weight: 300; text-align: left; line-height: 1.3; font-size: 14px; margin: 0; padding: 0;" align="left"></th>
                    </tr></table></th>
        </tr></tbody></table><table class="row" style="border-spacing: 0; border-collapse: collapse; vertical-align: top; text-align: left; width: 100%; position: relative; display: table; padding: 0;"><tbody><tr style="vertical-align: top; text-align: left; padding: 0;" align="left"><th class="small-12 large-4 columns first" style="width: 177.33333px; color: #5F5F5F; font-family: Roboto, Helvetica, Arial, sans-serif; font-weight: 300; text-align: left; line-height: 1.3; font-size: 14px; margin: 0 auto; padding: 0 20px;" align="left">
                <table class="callout" style="border-spacing: 0; border-collapse: collapse; vertical-align: top; text-align: left; width: 100%; margin-bottom: 16px; padding: 0;"><tbody><tr style="vertical-align: top; text-align: left; padding: 0 50px;" align="left"><th class="callout-inner secondary" style="color: #5F5F5F; font-family: Roboto, Helvetica, Arial, sans-serif; font-weight: 300; text-align: left; line-height: 1.3; font-size: 14px; width: 100%; background: #fff; margin: 0; padding: 0 20px; border: 1px none #444444;" align="left" bgcolor="#fff">
                            <table class="row" style="border-spacing: 0; border-collapse: collapse; vertical-align: top; text-align: left; width: 100%; position: relative; display: table; padding: 0;"><tbody><tr style="vertical-align: top; text-align: left; padding: 0;" align="left"><th class="small-12 large-4 columns first" style="width: 33.33333%; color: #5F5F5F; font-family: Roboto, Helvetica, Arial, sans-serif; font-weight: 300; text-align: left; line-height: 1.3; font-size: 14px; margin: 0 auto; padding: 0;" align="left">
                                        <table style="border-spacing: 0; border-collapse: collapse; vertical-align: top; text-align: left; width: 100%; padding: 0;"><tbody><tr style="vertical-align: top; text-align: left; padding: 0;" align="left"><th style="color: #5F5F5F; font-family: Roboto, Helvetica, Arial, sans-serif; font-weight: 300; text-align: left; line-height: 1.3; font-size: 14px; margin: 0; padding: 0;" align="left">
                                                    <h5 style="color: #666666; text-align: center; font-family: Roboto, Helvetica, Arial, sans-serif; font-weight: normal; line-height: 1.3; word-wrap: normal; font-size: 20px; margin: 0 0 10px; padding: 0;" class="text-center" align="center"><span style="font-weight: 500; padding: 0;">{!! $hospital->name !!}</span> </h5>
                                                    <p style="font-weight: 600; color: #5F5F5F; font-family: Roboto, Helvetica, Arial, sans-serif; text-align: left; line-height: 1.3; font-size: 14px; margin: 0 0 10px; padding: 0;" align="left">Discount Code : {!! $hospital->code !!}</p>
                                                    <p style="font-weight: 600; color: #5F5F5F; font-family: Roboto, Helvetica, Arial, sans-serif; text-align: left; line-height: 1.3; font-size: 14px; margin: 0 0 10px; padding: 0;" align="left">Validation Time  : {!! $discount !!}</p>

                                                </th>
                                            </tr></tbody></table><table class="discount-table" style="border-spacing: 0; border-collapse: collapse; vertical-align: top; text-align: left; width: 100%; padding: 0;"><tbody><tr style="vertical-align: top; text-align: left; padding: 0;" align="left"><th style="color: #fff; font-family: Roboto, Helvetica, Arial, sans-serif; font-weight: 700; text-align: center; line-height: 1.3; font-size: 14px; background: #ed1c24; margin: 1px; padding: 7px 10px;" align="center" bgcolor="#ed1c24">Services Name</th>
                                                <th style="color: #fff; font-family: Roboto, Helvetica, Arial, sans-serif; font-weight: 700; text-align: center; line-height: 1.3; font-size: 14px; background: #ed1c24; margin: 1px; padding: 7px 10px;" align="center" bgcolor="#ed1c24">Discount price</th>
                                            </tr>

                                            @foreach($services as $service)
                                                <tr style="vertical-align: top; text-align: left; padding: 0;" align="left"><td style="word-wrap: break-word; -webkit-hyphens: auto; -moz-hyphens: auto; hyphens: auto; border-collapse: collapse !important; vertical-align: top; text-align: center; color: #5F5F5F; font-family: Roboto, Helvetica, Arial, sans-serif; font-weight: 300; line-height: 1.3; font-size: 14px; border-bottom-style: solid; border-bottom-color: #fff; border-bottom-width: 1px; background: #f2f2f2; margin: 1px; padding: 7px 10px;" align="center" bgcolor="#f2f2f2" valign="top"> {!! $service['service_name'] !!}</td>
                                                    <td style="word-wrap: break-word; -webkit-hyphens: auto; -moz-hyphens: auto; hyphens: auto; border-collapse: collapse !important; vertical-align: top; text-align: center; color: #5F5F5F; font-family: Roboto, Helvetica, Arial, sans-serif; font-weight: 300; line-height: 1.3; font-size: 14px; border-bottom-style: solid; border-bottom-color: #fff; border-bottom-width: 1px; background: #f2f2f2; margin: 1px; padding: 7px 10px;" align="center" bgcolor="#f2f2f2" valign="top">{!! $service['discount'] !!}</td>
                                                </tr>
                                            @endforeach
                                            </tbody></table></th>
                                </tr></tbody></table></th>
                        <th class="expander" style="visibility: hidden; width: 0; color: #5F5F5F; font-family: Roboto, Helvetica, Arial, sans-serif; font-weight: 300; text-align: left; line-height: 1.3; font-size: 14px; margin: 0; padding: 0;" align="left"></th>
                    </tr></tbody></table></th>
        </tr></tbody></table><br><br>
                            <p style="color: #5F5F5F; font-family: Roboto, Helvetica, Arial, sans-serif; font-weight: 300; text-align: left; line-height: 1.3; font-size: 14px; margin: 0 0 10px 20px; padding: 0px 20px;" align="left">Thank you for using Daktarbhai.</p>
                            <p style="color: #5F5F5F; font-family: Roboto, Helvetica, Arial, sans-serif; font-weight: 300; text-align: left; line-height: 1.3; font-size: 14px; margin: 0 0 10px 20px; padding: 0px 20px;" align="left">The Daktarbhai Team.</p>

@endsection